server:
  port: 8462
logging:
  file: /java/C2S_LOGS/staff-ui-api/StaffUiApi.log
info:
  component: Staff Ui Api
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
feign:
  httpclient:
    enabled: true
security:
  oauth2:
    client:
      client-id: staff-ui-api
c2s:
  staff-ui-api:
    # Please configure valid config below to connect to UAA server
    # Configure base-url, client-id, client-secret per environment
    oauth2:
      base-url: http://localhost/uaa
      client:
        client-id: staff-ui
        client-secret: changeit
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /staff-ui-api